import json
import os


def check_sections():
    """
    Enhanced section validation with comprehensive checks.
    Validates all output files and displays detailed statistics.
    """
    
    # Define paths relative to project root
    project_root = os.path.dirname(
        os.path.dirname(os.path.abspath(__file__))
    )
    output_dir = os.path.join(project_root, "data", "output")
    
    toc_file = os.path.join(output_dir, "usb_pd_toc.jsonl")
    spec_file = os.path.join(output_dir, "usb_pd_spec.jsonl")
    validation_file = os.path.join(
        output_dir,
        "validation_report.json"
    )
    
    # Check if files exist
    files_missing = False
    
    if not os.path.exists(toc_file):
        print(f"[ERROR] TOC file not found: {toc_file}")
        print("Please run: python src/usb_pd_parser.py")
        files_missing = True
        
    if not os.path.exists(spec_file):
        print(f"[ERROR] Spec file not found: {spec_file}")
        print("Please run: python src/usb_pd_parser.py")
        files_missing = True
    
    if not os.path.exists(validation_file):
        print(f"[WARNING] Validation report not found: "
              f"{validation_file}")
        print("This file should be auto-generated by the parser.")
    
    if files_missing:
        return

    # Check TOC sections
    toc_count = 0
    toc_sample = []
    with open(toc_file, "r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            if line.strip():
                toc_count += 1
                if i < 3:  # Get first 3 for sample
                    toc_sample.append(json.loads(line))

    # Check spec sections
    spec_count = 0
    spec_sample = []
    with open(spec_file, "r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            if line.strip():
                spec_count += 1
                if i < 3:  # Get first 3 for sample
                    spec_sample.append(json.loads(line))
    
    # Load validation report if exists
    validation_data = None
    if os.path.exists(validation_file):
        with open(validation_file, "r", encoding="utf-8") as f:
            validation_data = json.load(f)

    # Print comprehensive report
    print("=" * 70)
    print("USB PD Parser - Validation Results")
    print("=" * 70)
    
    print("\n📊 FILE STATUS:")
    print(f"  ✓ TOC File:        {toc_file}")
    print(f"  ✓ Spec File:       {spec_file}")
    if validation_data:
        print(f"  ✓ Validation:      {validation_file}")
    else:
        print(f"  ⚠ Validation:      Not found")
    
    print("\n📈 EXTRACTION STATISTICS:")
    print(f"  TOC Sections:      {toc_count:,}")
    print(f"  Content Sections:  {spec_count:,}")
    print(f"  Match Status:      "
          f"{'✓ Matched' if toc_count == spec_count else '⚠ Mismatch'}")
    
    if validation_data:
        print("\n📋 VALIDATION REPORT:")
        summary = validation_data.get("summary", {})
        page_cov = summary.get("page_coverage", {})
        
        print(f"  Total Pages:       "
              f"{page_cov.get('total_pages', 'N/A'):,}")
        print(f"  Pages Covered:     "
              f"{page_cov.get('pages_covered', 'N/A'):,}")
        print(f"  Pages Missing:     "
              f"{page_cov.get('pages_missing', 'N/A'):,}")
        print(f"  Coverage:          "
              f"{page_cov.get('coverage_percentage', 'N/A')}%")
        print(f"  Status:            "
              f"{validation_data.get('validation_status', 'N/A')}")
        
        toc_analysis = validation_data.get("toc_analysis", {})
        print(f"\n  TOC Hierarchy:")
        print(f"    Levels:          "
              f"{toc_analysis.get('hierarchy_levels', 'N/A')}")
        
        content_analysis = validation_data.get("content_analysis", {})
        print(f"\n  Content Quality:")
        print(f"    With Content:    "
              f"{content_analysis.get('sections_with_content', 'N/A'):,}")
        print(f"    Without Content: "
              f"{content_analysis.get('sections_without_content', 'N/A'):,}")
    
    print("\n🔍 SAMPLE DATA (First 3 entries):")
    print("\n  TOC Sample:")
    for i, entry in enumerate(toc_sample, 1):
        print(f"    {i}. Section: {entry.get('section_id', 'N/A')} - "
              f"{entry.get('title', 'N/A')[:50]}...")
    
    print("\n  Content Sample:")
    for i, entry in enumerate(spec_sample, 1):
        content_preview = entry.get('content', 'N/A')[:50]
        print(f"    {i}. Section: {entry.get('section_id', 'N/A')} - "
              f"{content_preview}...")
    
    print("\n" + "=" * 70)
    
    # Determine overall status
    if toc_count > 0 and spec_count > 0:
        if validation_data:
            status = validation_data.get('validation_status', 'UNKNOWN')
            if status == "PASS":
                print("[✓ SUCCESS] All validations PASSED!")
            elif status == "PARTIAL":
                print("[⚠ PARTIAL] Extraction completed with warnings.")
            else:
                print("[✗ FAILED] Validation failed. Check report.")
        else:
            print("[✓ SUCCESS] Extraction completed!")
            print("[⚠ WARNING] Validation report missing.")
    else:
        print("[✗ ERROR] No sections found. Check parser output.")
    
    print("=" * 70)


if __name__ == "__main__":
    check_sections()